
# THIS FILE WILL EVENTUALLY BE GENERATED BY SETUP.PY
short_version = '0.0'
version = '0.0'
full_version = '0.00'
#git_revision = '8727aa13d37ca0ca223bc057adf9978082295566'
#release = True

#if not release:
    #version = full_version
